spring.application.name=demo

# PostgreSQL 연결
spring.datasource.url=jdbc:postgresql://localhost:5432/myblogapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
# JPA 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL 쿼리 출력 (모든 로그 유지)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL 로그 레벨
logging.level.org.hibernate.tool.schema=DEBUG

# 쿼리 로그 레벨 (Spring Boot 3.x + PostgreSQL)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.thymeleaf.cache=false
